### ISSUE TITLE
Broken yarn.lock

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1625]
Hello :slightly_smiling_face: 

The [yarn.lock](https://github.com/brainly/style-guide/blob/master/yarn.lock) file is most likely broken because when I perform a fresh installation by following the steps in the CONTRIBUTING.md file, I get errors
https://github.com/brainly/style-guide/blob/8d4cc18417010b760c6341bf6bb6747500ab4ccf/CONTRIBUTING.md#L22-L29

Terminal output:
```
Sahins-Mac:style-guide seahindeniz$ yarn build
yarn run v1.17.3
$ gulp build
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/seahindeniz/Projects/style-guide/node_modules/natives/index.js:137:5)
    at require (/Users/seahindeniz/Projects/style-guide/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/Users/seahindeniz/Projects/style-guide/node_modules/natives/index.js:137:5)
    at require (/Users/seahindeniz/Projects/style-guide/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/Users/seahindeniz/Projects/style-guide/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/seahindeniz/Projects/style-guide/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/seahindeniz/Projects/style-guide/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
$ node -v
v10.16.3

$ gulp -v
CLI version: 2.2.0
Local version: 3.9.1

$ yarn -v
1.17.3

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.4
BuildVersion:   18E226
```

**Temporary fix**
To start building without having a ReferenceError, I remove the yarn.lock file and execute the `yarn install && yarn build` again and it works.

Could you please check this problem? I think it would be best if contributing steps is being reviewed.

Thanks in advance!

**Comment by burakukula** [comment]
@seahindeniz 👋 Hey! thx a lot for reporting! 👌 We will have a look on this and take a look on contribution steps as well.

**Comment by matzimowski** [comment]
@seahindeniz is it still valid?
